import { NextResponse, NextRequest } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(request: NextRequest) {
  try {
    const { 
      cryptoAmount,
      selectedCrypto,
      nairaAmount,
      exchangeRate,
      bankName,
      accountName,
      accountNumber,
      walletAddress
    } = await request.json();

    // Input validation
    if (!cryptoAmount || !selectedCrypto || !nairaAmount || !bankName || !accountName || !accountNumber || !walletAddress) {
      return NextResponse.json(
        {
          error: 'Missing required fields',
          message: 'Please provide all transaction and bank details',
        },
        { status: 400 }
      );
    }

    // Generate transaction reference
    const transactionRef = `OFFRAMP-${Date.now().toString().slice(-8)}`;
    const timestamp = new Date().toLocaleString();

    // Create nodemailer transporter
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.GMAIL_USER,
        pass: process.env.GMAIL_APP_PASSWORD,
      },
    });

    // Email content
    const mailOptions = {
      from: process.env.GMAIL_USER,
      to: "ramplify.org@gmail.com",
      subject: `🔄 New Offramp Transaction - ${transactionRef}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #dc2626;">🔄 New Offramp Transaction</h2>
          
          <div style="background-color: #fef2f2; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #dc2626;">
            <h3 style="margin-top: 0; color: #991b1b;">Transaction Details</h3>
            <p><strong>📋 Transaction ID:</strong> ${transactionRef}</p>
            <p><strong>🪙 Crypto Amount:</strong> ${cryptoAmount} ${selectedCrypto}</p>
            <p><strong>💰 Naira Amount:</strong> ₦${parseFloat(nairaAmount).toLocaleString()}</p>
            <p><strong>📈 Exchange Rate:</strong> 1 ${selectedCrypto} = ₦${parseFloat(exchangeRate).toLocaleString()}</p>
            <p><strong>📱 Wallet Address:</strong> <code style="background-color: #e5e7eb; padding: 2px 4px; border-radius: 4px;">${walletAddress}</code></p>
            <p><strong>⏰ Time:</strong> ${timestamp}</p>
            <p><strong>🔄 Status:</strong> <span style="color: #dc2626; font-weight: bold;">Awaiting Crypto Transfer</span></p>
          </div>

          <div style="background-color: #f0f9ff; padding: 20px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #0ea5e9;">
            <h3 style="margin-top: 0; color: #0c4a6e;">Bank Details for Payment</h3>
            <p><strong>🏦 Bank Name:</strong> ${bankName}</p>
            <p><strong>👤 Account Name:</strong> ${accountName}</p>
            <p><strong>🔢 Account Number:</strong> <code style="background-color: #e5e7eb; padding: 2px 4px; border-radius: 4px; font-size: 16px;">${accountNumber}</code></p>
          </div>

          <div style="background-color: #fef3c7; padding: 15px; border-radius: 8px; border-left: 4px solid #f59e0b;">
            <p style="margin: 0;"><strong>⚠️ Action Required:</strong></p>
            <ol style="margin: 10px 0; padding-left: 20px;">
              <li>Wait for user to send <strong>${cryptoAmount} ${selectedCrypto}</strong> to the specified wallet</li>
              <li>Verify the crypto transaction on blockchain</li>
              <li>Send <strong>₦${parseFloat(nairaAmount).toLocaleString()}</strong> to the bank account above</li>
              <li>Confirm transaction completion with user</li>
            </ol>
          </div>

          <div style="margin-top: 20px; padding: 15px; background-color: #f9fafb; border-radius: 8px;">
            <p style="margin: 0; font-size: 12px; color: #6b7280;">
              This email was automatically generated by Ramplify when a user initiated an offramp transaction.
            </p>
          </div>
        </div>
      `,
    };

    // Send email
    await transporter.sendMail(mailOptions);

    return NextResponse.json(
      {
        success: true,
        transactionRef,
        message: 'Offramp transaction notification sent successfully',
      },
      { status: 200 }
    );

  } catch (error) {
    console.error('Error sending offramp email notification:', error);
    return NextResponse.json(
      {
        error: 'Internal server error',
        message: 'Failed to send email notification',
      },
      { status: 500 }
    );
  }
}
